<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>RemoveTaxRate</name>
   <tag></tag>
   <elementGuidId>fb2a3b1a-75c6-4fee-8a25-9735046e3976</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n    \&quot;version\&quot;: ${tax-category-version},\n    \&quot;actions\&quot;: [\n        {\n            \&quot;action\&quot; : \&quot;removeTaxRate\&quot;,\n            \&quot;taxRateId\&quot; : \&quot;${taxRateID}\&quot;\n          }\n    ]\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer {{ctp_access_token}}</value>
      <webElementGuid>04ef6339-70a9-49af-bcce-8da1b1b94d73</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>2286ebca-e5ee-4f47-aed2-2635b221a3a6</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>8.6.9</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${host}/${project-key}/tax-categories/${tax-category-id}</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.host</defaultValue>
      <description></description>
      <id>f0fc072e-a998-4c65-aeb4-782fd314c4ef</id>
      <masked>false</masked>
      <name>host</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.project-key</defaultValue>
      <description></description>
      <id>c02a4dde-f63c-4224-a622-c499af20c6fc</id>
      <masked>false</masked>
      <name>project-key</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.tax-category-id</defaultValue>
      <description></description>
      <id>bbfccc37-f5e8-4c17-9434-0dabfa5f8c5f</id>
      <masked>false</masked>
      <name>tax-category-id</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.tax-category-version</defaultValue>
      <description></description>
      <id>0d0d73ed-55bb-464c-ae9c-e53b1a3b5db0</id>
      <masked>false</masked>
      <name>tax-category-version</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.taxRateID</defaultValue>
      <description></description>
      <id>de7f4c7f-afe0-474f-8c8b-de73e6980c91</id>
      <masked>false</masked>
      <name>taxRateID</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
