<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>ChangeLocalizedEnumValueOrder</name>
   <tag></tag>
   <elementGuidId>31d294f5-1ca5-47e9-b0cb-cf22623ad00b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n    \&quot;version\&quot;: ${product-type-version},\n    \&quot;actions\&quot;: [\n        {\n            \&quot;action\&quot; : \&quot;changeLocalizedEnumValueOrder\&quot;,\n            \&quot;attributeName\&quot; : \&quot;your-attribute-name\&quot;,\n            \&quot;values\&quot; : [ {\n              \&quot;key\&quot; : \&quot;localized enum key 1\&quot;,\n              \&quot;label\&quot; : {\n                \&quot;en\&quot; : \&quot;English label for enum key 1\&quot;,\n                \&quot;de\&quot; : \&quot;German label for enum key 1\&quot;\n              }\n            }, {\n              \&quot;key\&quot; : \&quot;localized enum key 2\&quot;,\n              \&quot;label\&quot; : {\n                \&quot;en\&quot; : \&quot;English label for enum key 2\&quot;,\n                \&quot;de\&quot; : \&quot;German label for enum key 2\&quot;\n              }\n            }, {\n              \&quot;key\&quot; : \&quot;localized enum key 3\&quot;,\n              \&quot;label\&quot; : {\n                \&quot;en\&quot; : \&quot;English label for enum key 3\&quot;,\n                \&quot;de\&quot; : \&quot;German label for enum key 3\&quot;\n              }\n            } ]\n          }\n    ]\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer {{ctp_access_token}}</value>
      <webElementGuid>58ea84bb-5a18-42bb-9b00-4c0b63aaa7b3</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>a9c8660c-3181-4456-b29b-30274edafa2e</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>8.6.9</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${host}/${project-key}/product-types/${product-type-id}</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.host</defaultValue>
      <description></description>
      <id>d180a3cb-6af1-4778-bab4-113c198a4fe7</id>
      <masked>false</masked>
      <name>host</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.project-key</defaultValue>
      <description></description>
      <id>07b6d491-b16b-40da-abc1-7c057685fbd6</id>
      <masked>false</masked>
      <name>project-key</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.product-type-id</defaultValue>
      <description></description>
      <id>18d21bc9-fa4e-4156-b615-5814b31ec979</id>
      <masked>false</masked>
      <name>product-type-id</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.product-type-version</defaultValue>
      <description></description>
      <id>230ce895-b74a-429f-b1bb-139a3bb986e6</id>
      <masked>false</masked>
      <name>product-type-version</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
